Update shell scripts to pass newer/deeper shellcheck.
shellcheck is updated in Debian 12 (bookworm) and performs a more immersive sweep based on code branching.

diff --git a/common b/common
--- a/common
+++ b/common
@@ -80,12 +80,12 @@ fatal=5
 log_level=${log_level:-$debug}
 
 
-debug()    { logstd $debug    "DEBUG - [$$] - $*"; }
-info()     { logstd $info     "INFO - $*"; }
-warn()     { logstd $warn     "WARN - $*"; }
-error()    { logerr $error    "ERROR - $*"; }
-critical() { logerr $critical "CRITIAL - $*"; }
-fatal()    { logerr $fatal    "FATAL - $*"; exit 1; }
+debug()    { logstd "$debug"    "DEBUG - [$$] - $*"; }
+info()     { logstd "$info"     "INFO - $*"; }
+warn()     { logstd "$warn"     "WARN - $*"; }
+error()    { logerr "$error"    "ERROR - $*"; }
+critical() { logerr "$critical" "CRITIAL - $*"; }
+fatal()    { logerr "$fatal"    "FATAL - $*"; exit 1; }
 
 
 logstd() {
@@ -525,5 +525,5 @@ iec_size_format() {
             byte_size=$((byte_size/1024))
         fi
     done
-    printf "%.2f YiB\\n" $byte_size
+    printf "%.2f YiB\\n" "$byte_size"
 }
